<a href="https://colab.research.google.com/github/ttoutlook/Colab-TensorFlow/blob/master/eager_execution_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
tf.enable_eager_execution()

In [9]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))
print(tf.encode_base64('hello world'))

# operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [10]:
x = tf.matmul([[1]],[[2,3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [11]:
import numpy as np

ndarray = np.ones([3,3])

print('TensorFlow operations convert numpy arrays to Tensors automatically')
tensor = tf.multiply(ndarray, 42)
print(tensor)

print("And numpy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor,1))

print('The .numpy() method explictly converts a Tensor to a numpy array')
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And numpy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explictly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [12]:
# GPU acceleration
x = tf.random_uniform([3,3])

print('Is there a GPU available: ')
print(tf.test.is_gpu_available())

print('Is the Tensor on GPU #0: ')
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
False
Is the Tensor on GPU #0: 
False
